### ISSUE TITLE
how do I install this?

### ISSUE THREAD

**Issue by six-shooter** [FFS2309/Logitech-G19-s-Web-Browser#1]
I have downloaded lcdjni + jxbrowser and this package, but how do I install it?

**Comment by FFS2309** [comment]
I only ever ran it from my IDE, eclipse in my case, there I simply had lcdjni and jxbrowser set as referenced libraries and I could launch it from there.

I hope this helps you because sadly my G19s display is broken so I can't test it and make sure it works anymore :/
